SLASH_NOXTEST1 = "/noxtest";

local testformats = {
   Basics = {
      "{latency}",
      "{framerate}",
      "{24hours}",
      "{hours}",
      "{minutes}",
      "{ampm}",
      "{x}",
      "{y}",
      "{money}",
      "{hpregen}",
      "{manaregen}",
      "{hp}",
      "{hploss}",
      "{hp%}",
      "{maxhp}",
      "{mana}",
      "{manaloss}",
      "{mana%}",
      "{maxmana}",
      "{xp}",
      "{xptolevel}",
      "{xp%}",
      "{xptolevel%}",
      "{maxxp}",
      "{rest}",
      "{level}",
      "{ubs}",
      "{abs}",
      "{tbs}",
      "{mem}",
      "{memlimit}",
      "{restbonus}",
      "{restlimit}",
      "{ammo}",
      "{sessionttl}",
      "{levelttl}",
      "{bestttl}",
      "{totaltime}",
      "{sessiontime}",
      "{leveltime}",
      "{sessionxprate}",
      "{levelxprate}",
      "{income}",
      "{expense}",
      "{netincome}",
      "{incomerate}",
      "{expenserate}",
      "{netincomerate}",
   },
   Formats = {
      "{framerate:int}",
      "{framerate:dec}",
      "{totaltime:short}",
      "{totaltime:medium}",
      "{totaltime:long}",
      "{money:as gold}",
      "{money:as gold,dec,1}",
      "{money:as silver}",
      "{money:as silver,dec,1}",
      "{money:as copper}",
      "{money:as copper,dec,1}",
      "{money:gold}",
      "{money:gold,1}",
      "{money:silver}",
      "{money:silver,1}",
      "{money:copper}",
      "{money:copper,1}",
      "{money:long}",
      "{money:long,1}",
      "{money:long,1,1}",
      "{money:short}",
      "{money:short,1}",
      "{money:short,1,1}",
      "{money:numeric}",
      "{money:numeric,1}",
      "{money:compact}",
      "{money:compact,1}",
      "{mem:kb}",
      "{mem:mb}",
      "{mem:mb,dec}",
      "{mem:mb,int}",
   },
   Combat = {
      "{dps}",
      "{hps}",
      "{petdps}",
      "{totaldamage}",
      "{totalheal}",
      "{combatduration}",
      "{meleehits}",
      "{meleemisses}",
      "{meleecrits}",
      "{meleehits%}",
      "{meleemisses%}",
      "{meleecrits%}",
      "{nonmeleehits}",
      "{nonmeleemisses}",
      "{nonmeleecrits}",
      "{nonmeleehits%}",
      "{nonmeleemisses%}",
      "{nonmeleecrits%}",
      "{healhits}",
      "{healmisses}",
      "{healcrits}",
      "{healhits%}",
      "{healmisses%}",
      "{healcrits%}",
      "{sessiondps}",
      "{sessionhps}",
      "{sessionpetdps}",
      "{sessiontotaldamage}",
      "{sessiontotalheal}",
      "{sessioncombatduration}",
      "{sessionmeleehits}",
      "{sessionmeleemisses}",
      "{sessionmeleecrits}",
      "{sessionmeleehits%}",
      "{sessionmeleemisses%}",
      "{sessionmeleecrits%}",
      "{sessionnonmeleehits}",
      "{sessionnonmeleemisses}",
      "{sessionnonmeleecrits}",
      "{sessionnonmeleehits%}",
      "{sessionnonmeleemisses%}",
      "{sessionnonmeleecrits%}",
      "{sessionhealhits}",
      "{sessionhealmisses}",
      "{sessionhealcrits}",
      "{sessionhealhits%}",
      "{sessionhealmisses%}",
      "{sessionhealcrits%}",
      "{kills}",
      "{xpperkill}",
      "{killstolevel}",
   },
   Equipment = {
      "{equipslot:chest}",
      "{equipname:chest}",
      "{currdurability:chest}",
      "{maxdurability:chest}",
      "{durability%:chest}",
      "{repaircost:chest}",
      "{totalrepaircost}",
      "{totalcurrdurability}",
      "{totalmaxdurability}",
      "{totaldurability%}",
   },
   ["Equipment Slots"] = {
      "{equipname:head}",
      "{equipname:shoulders}",
      "{equipname:chest}",
      "{equipname:wrists}",
      "{equipname:hands}",
      "{equipname:waist}",
      "{equipname:legs}",
      "{equipname:feet}",
      "{equipname:mainhand}",
      "{equipname:offhand}",
      "{equipname:ranged}",
      "{equipname:finger1}",
      "{equipname:finger2}",
      "{equipname:trinket1}",
      "{equipname:trinket2}",
      "{equipname:neck}",
      "{equipname:back}",
      "{equipname:shirt}",
      "{equipname:tabard}",
      "{equipname:ammo}",
      "{equipname:shield}",
      "{equipname:cloak}",
      "{equipname:ring1}",
      "{equipname:ring2}",
      "{equipname:necklace}",
      "{equipname:bracers}",
      "{equipname:helm}",
      "{equipname:gloves}",
      "{equipname:pants}",
      "{equipname:boots}",
      "{equipname:pauldrons}",
      "{equipname:weapon}",
      "{equipname:gun}",
      "{equipname:bow}",
      "{equipname:torso}",
      "{equipname:pendant}",
      "{equipname:robe}",
      "{equipname:skirt}",
      "{equipname:kilt}",
      "{equipname:leggings}",
      "{equipname:belt}",
      "{equipname:tunic}",
      "{equipname:hat}",
      "{equipname:goggles}",
      "{equipname:gauntlets}",
      "{equipname:shoes}",
      "{equipname:vest}",
      "{equipname:breastplate}",
   },
   Honor = {
      "{lifetimehk}",
      --"{lifetimedk}",
      "{lifetimerank}",
      --"{lastweekhk}",
      --"{lastweekdk}",
      --"{lastweekcp}",
      --"{lastweekstanding}",
      "{yesterdayhk}",
      --"{yesterdaydk}",
      "{yesterdaycp}",
      "{sessionhk}",
      --"{sessiondk}",
      "{currentrank}",
      "{currentstanding}",
      --"{thisweekhk}",
      --"{thisweekhonor}",
      "{rankprogress}",
      "{yesterdayhonor}",
      --"{lastweekhonor}",
      "{todayhk}",
      --"{todaydk}",
      "{todayhonor}",
   },
   Player = {
      "{class}",
      "{name}",
      "{subzone}",
      "{shortzone}",
      "{realm}",
      "{zone}",
      "{realzone}",
      "{sex}",
      "{race}",
      "{faction}",
      "{strength}",
      "{agility}",
      "{stamina}",
      "{intellect}",
      "{spirit}",
      "{armor}",
      "{resistholy}",
      "{resistarcane}",
      "{resistfire}",
      "{resistnature}",
      "{resistfrost}",
      "{resistshadow}",
   },
   Skill = {
      "{skillrank:Professions 1}",
      "{skillmax:Professions 1}",
      "{skillname:Professions 1}",
   },
};
  
function NoxTester_OnLoad()
   SlashCmdList["NOXTEST"] = NoxTester_SlashCmd;
end

function NoxTester_OnEvent()
end

local channel;
local lang;

function NoxTester_SlashCmd(msg)
--   LoggingChat(1);
--   JoinChannelByName("NoxTestChannel");
--   channel = GetChannelName("NoxTestChannel");
--   lang = GetDefaultLanguage("player");
   if (msg and testformats[msg]) then
      NoxTester_Test(testformats[msg]);
   else
      NoxTester_Test(testformats);
   end
--   LeaveChannelByName("NoxTestChannel");
--   LoggingChat(nil);
end

function NoxTester_Test(t)
   for k, v in pairs(t) do
      if type(v) == 'table' then
         DEFAULT_CHAT_FRAME:AddMessage(k);
         --print(v.category .. ':');
         --SendChatMessage(k .. ':', "CHANNEL", lang, channel);
         --NoxTester_Test(v);
         --DEFAULT_CHAT_FRAME:AddMessage();
      else
         local val = NoxInformationBar_FormatText(v) or '(nil)';
         DEFAULT_CHAT_FRAME:AddMessage('  ' .. v .. ' = ' .. val);
         --SendChatMessage('  ' .. v .. ' = ' .. val, "CHANNEL", lang, channel);
      end
   end
end
